import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import {useAuthState} from 'react-firebase-hooks/auth'
import { auth } from '@/firebase'
import SignIn from '@/components/SignIn'
import ChatRoom from '@/components/ChatRoom'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [user] = useAuthState(auth)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='App'>
        <header>

        </header>

        <section>
          {user ? <ChatRoom/> : <SignIn/>}
        </section>
      </main>
    </>
  )
}
